### ISSUE TITLE
Oak-Compact: Oak run jars not found

### ISSUE THREAD

**Issue by stephenpfaff** [SixDimensions/AEM-Tools#3]
Script wont find oak run jar files unless the repository folder exists exactly at /opt, consider making it find the jar folder relatively to script location.

**Comment by dwaynehale** [comment]
As per https://github.com/SixDimensions/AEM-Tools/issues/2
This is a configurable step, or could likely be passed in, please see the -H option for details...
Configurables as follows:

  echo -e \\n"Usage: run-compact.sh [OPTION]"\\n
  echo "Mandatory arguments to long options are mandatory for short options too."
  echo "-d       Path to repository to compact"
  echo "-v       The version of oak-compact.jar to use."
  echo "-m       The mode of cleanup, this can currently be rm-unreferenced or rm-all"
  echo "-b       Set to true to backup the repository before compacting, backup will occur in same directory as repo."
  echo "-j       Specify additional JVM options for oak run jar (such as memory requirements)"
  echo "-p       Specify the crx-quickstart location for locating the pid file."
  echo "-i       Instance Type, can be publish to use configured start/stop scripts for a publish instance (must configure)"
  echo -e "-H       displays this help and then exits"\\n
  echo -e "Example: run-compact.sh -d /opt/aem/crx-quickstart/repository/segmentstore -v 1.0.8 -m rm-all"
  exit
}
# script configurations
##the start and stop need to be configured for the modes you plan to run this with (-i).
START='/etc/init.d/aem-author start'
STOP='/etc/init.d/aem-author stop'
ITYPE='' #blank for author, this is for internal error reporting.
OAK_JARS_LOCATION="/opt/oak-compact"
COMPACTION_USER="cq"
SLEEPTIME='20s'
TIMEOUT=5
# email notification configuration
HOST="HOSTNAME"
TO="youremail@email.com"


If you specify the PID file, the script expects to stop and start the instance...
